#pragma once

// PARTIES_VERSION_* macros are generated by CMake from git tags.
// The generated header lives at ${CMAKE_BINARY_DIR}/generated/parties/version_gen.h
#include <parties/version_gen.h>

namespace parties {

constexpr const char* APP_NAME = "Parties";
constexpr const char* APP_VERSION = PARTIES_VERSION_STR;

} // namespace parties
